version: '3'
 
volumes:
  traefik-ssl-certs:
    driver: local
  my-db:
    driver: local

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'toktik-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - back-office

  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.7
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - ./:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-ssl-certs:/ssl-certs
    labels:
      - "traefik.http.middlewares.set-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.set-cors.headers.accesscontrolallowheaders=*,X-Custom-Header,X-Video-Name"
      - "traefik.http.middlewares.set-cors.headers.accesscontrolalloworiginlist=http://localhost:8000"
      - "traefik.http.middlewares.set-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.set-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.set-cors.headers.addvaryheader=true"
      - "traefik.http.middlewares.stripprefix.stripprefix.prefixes=/auth,/api"
      - "traefik.http.middlewares.my-auth.forwardauth.address=http://auth:7887/"
      - "traefik.http.middlewares.my-auth.forwardauth.trustforwardheader=true"
      - "traefik.http.middlewares.my-auth.forwardauth.authresponseheaders=X-Username,Access-Control-Allow-Origin,Access-Control-Allow-Headers"
    networks:
      - front-office
      - back-office

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - back-office
    depends_on:
      - traefik

  back-end:
    build:
      context: ./scalable-p2-backend
      dockerfile: Dockerfile
    networks:
      - back-office
    depends_on:
      - db-svc
    restart: always
    labels:
      - traefik.http.routers.back-end.rule=(Host(`toktik.localhost`) && PathPrefix(`/api/`))
      - traefik.http.services.back-end.loadbalancer.server.port=7000
      - traefik.http.routers.back-end.middlewares=stripprefix,set-cors,my-auth
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 

  front-end:
    build:
      context: ./scalable-p2-frontend
      dockerfile: Dockerfile
    environment:
      API_GATEWAY_URL: "toktik.localhost"
    ports:
      - "8000:8000"
    depends_on:
      - traefik
    networks:
      - front-office

  db-svc:
    build:
      context: ./scalable-p2-db
      dockerfile: Dockerfile
    networks:
      - back-office
    restart: always
    depends_on:
      - mysql
      - traefik
    ports:
      - "8083:8083"

  auth:
    build:
      context: ./scalable-p2-user-service
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - traefik
    networks:
      - back-office
      - front-office 
    labels:
      - traefik.http.routers.auth.rule=(Host(`toktik.localhost`) && PathPrefix(`/auth/`))
      - traefik.http.services.auth.loadbalancer.server.port=7887
      - traefik.http.routers.auth.middlewares=stripprefix
    restart: always

networks:
  front-office: # frontend and api gateway
  back-office: # backend microservices and api gateway

