apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-deployment
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-deployment
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - image: ghcr.io/help-me-someone/scalable-p2-user-svc/toktik-auth:latest
        name: toktik-auth
        ports:
        - name: auth-pod-port
          containerPort: 7887
        env:
        - name: ALLOWED_ORIGIN
          value: http://localhost

        - name: DB_IP
          value: toktik-mysql-svc.default.svc.cluster.local

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key:  DB_USER        

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
        resources: {}
status: {}
