apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-deployment
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-deployment
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - image: ghcr.io/help-me-someone/scalable-p2-backend/toktik-backend:latest
        name: toktik-backend
        ports:
        - name: back-pod-port
          containerPort: 7000
        resources: {}
        env:
        - name: DB_IP
          value: toktik-mysql-svc.default.svc.cluster.local
        - name: REDIS_IP
          value: redis-svc.default.svc.cluster.local
        - name: MODE
          value: DEBUG
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key:  DB_USER        
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
        - name: ALLOWED_ORIGIN
          value: http://localhost
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
status: {}
