apiVersion: v1
kind: Service
metadata:
  name: toktik-mysql-svc
  labels:
    app: toktik-mysql-deployment
spec:
  ports:
    - port: 3306
  selector:
    app: toktik-mysql-deployment
    tier: mysql
  clusterIP: None
